
name: Building release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_release:
    name: Build Release
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Determine version
        run: echo "::set-output name=version::$(python ./PdfTranslator.pyw --version)"
        id: version
      - name: Create executable
        run: pyinstaller -w ./PdfTranslator.pyw
      - name: Zip Folder
        run: Compress-Archive -Path ./dist/PdfTranslator/* -DestinationPath ./PdfTranslator.zip
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: v${{ steps.version.outputs.version }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./PdfTranslator.zip
          asset_name: PdfTranslator_${{ steps.version.outputs.version }}.zip
          asset_content_type: application/zip
